--------------------------------------------------------------------------------
-- V1 - LIMPEZA DE OBJETOS EXISTENTES (IDEMPOTENCIA) + DDL DAS TABELAS CORE
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 0. LIMPEZA DE OBJETOS EXISTENTES (IDEMPOTENCIA)
--------------------------------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_AUDITORIA_CONSULTA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE AUDITORIA_LOG CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FATO_PAGAMENTO CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CONSULTA CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PET CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE VETERINARIO CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TUTOR CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

--------------------------------------------------------------------------------
-- 1. DDL - TABELAS CORE
--------------------------------------------------------------------------------

CREATE TABLE TUTOR (
    ID_TUTOR        NUMBER(6)       NOT NULL,
    NOME            VARCHAR2(100)   NOT NULL,
    CPF             VARCHAR2(14)    NOT NULL,
    TELEFONE        VARCHAR2(20),
    EMAIL           VARCHAR2(100),
    ENDERECO        VARCHAR2(200),
    DATA_CADASTRO   DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT KV_PK_TUTOR PRIMARY KEY (ID_TUTOR),
    CONSTRAINT KV_UQ_TUTOR_CPF UNIQUE (CPF)
);

CREATE TABLE VETERINARIO (
    ID_VETERINARIO  NUMBER(6)       NOT NULL,
    NOME            VARCHAR2(100)   NOT NULL,
    CRMV            VARCHAR2(20)    NOT NULL,
    ESPECIALIDADE   VARCHAR2(60),
    TELEFONE        VARCHAR2(20),
    EMAIL           VARCHAR2(100),
    CONSTRAINT KV_PK_VET PRIMARY KEY (ID_VETERINARIO),
    CONSTRAINT KV_UQ_VET_CRMV UNIQUE (CRMV)
);

CREATE TABLE PET (
    ID_PET          NUMBER(6)       NOT NULL,
    NOME            VARCHAR2(60)    NOT NULL,
    ESPECIE         VARCHAR2(30)    NOT NULL,
    RACA            VARCHAR2(60),
    DATA_NASCIMENTO DATE            NOT NULL,
    SEXO            CHAR(1)         NOT NULL,
    ID_TUTOR        NUMBER(6)       NOT NULL,
    CONSTRAINT KV_PK_PET PRIMARY KEY (ID_PET),
    CONSTRAINT KV_CK_PET_SEXO CHECK (SEXO IN ('M','F')),
    CONSTRAINT KV_FK_PET_TUTOR FOREIGN KEY (ID_TUTOR) REFERENCES TUTOR(ID_TUTOR)
);

CREATE TABLE CONSULTA (
    ID_CONSULTA     NUMBER(6)       NOT NULL,
    ID_PET          NUMBER(6)       NOT NULL,
    ID_VETERINARIO  NUMBER(6)       NOT NULL,
    DATA_CONSULTA   DATE            NOT NULL,
    TIPO_CONSULTA   VARCHAR2(40)    NOT NULL,
    DIAGNOSTICO     VARCHAR2(400),
    STATUS          VARCHAR2(20)    DEFAULT 'REALIZADA' NOT NULL,
    CONSTRAINT KV_PK_CONSULTA PRIMARY KEY (ID_CONSULTA),
    CONSTRAINT KV_CK_CONS_STATUS CHECK (STATUS IN ('AGENDADA','REALIZADA','CANCELADA')),
    CONSTRAINT KV_FK_CONS_PET FOREIGN KEY (ID_PET) REFERENCES PET(ID_PET),
    CONSTRAINT KV_FK_CONS_VET FOREIGN KEY (ID_VETERINARIO) REFERENCES VETERINARIO(ID_VETERINARIO)
);

CREATE TABLE FATO_PAGAMENTO (
    ID_PAGAMENTO    NUMBER(6)       NOT NULL,
    ID_CONSULTA     NUMBER(6)       NOT NULL,
    CLINICA         VARCHAR2(60)    NOT NULL,
    TIPO_PAGAMENTO  VARCHAR2(30)    NOT NULL,
    VALOR           NUMBER(10,2)    NOT NULL,
    DATA_PAGAMENTO  DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT KV_PK_FATO_PAG PRIMARY KEY (ID_PAGAMENTO),
    CONSTRAINT KV_CK_PAG_VALOR CHECK (VALOR >= 0),
    CONSTRAINT KV_FK_PAG_CONS FOREIGN KEY (ID_CONSULTA) REFERENCES CONSULTA(ID_CONSULTA)
);

CREATE TABLE AUDITORIA_LOG (
    ID_LOG          NUMBER GENERATED ALWAYS AS IDENTITY,
    USUARIO         VARCHAR2(60),
    OPERACAO        VARCHAR2(10),
    DATA_HORA       DATE,
    TABELA_AFETADA  VARCHAR2(30),
    VALORES_OLD     VARCHAR2(4000),
    VALORES_NEW     VARCHAR2(4000),
    CONSTRAINT KV_PK_AUDITORIA_LOG PRIMARY KEY (ID_LOG)
);