--------------------------------------------------------------------------------
-- V2 - CARGA DE DADOS INICIAIS (10 REGISTROS POR TABELA)
--------------------------------------------------------------------------------

-- TUTOR
INSERT INTO TUTOR (ID_TUTOR, NOME, CPF, TELEFONE, EMAIL, ENDERECO, DATA_CADASTRO) VALUES (1,'Ana Beatriz Souza','111.222.333-44','(11) 91234-5601','ana.souza@email.com','Rua das Flores, 120 - Sao Paulo/SP', DATE '2024-01-10');
INSERT INTO TUTOR (ID_TUTOR, NOME, CPF, TELEFONE, EMAIL, ENDERECO, DATA_CADASTRO) VALUES (2,'Carlos Eduardo Lima','222.333.444-55','(11) 91234-5602','carlos.lima@email.com','Av. Paulista, 900 - Sao Paulo/SP', DATE '2024-01-15');
INSERT INTO TUTOR (ID_TUTOR, NOME, CPF, TELEFONE, EMAIL, ENDERECO, DATA_CADASTRO) VALUES (3,'Beatriz Fernandes','333.444.555-66','(21) 91234-5603','beatriz.fernandes@email.com','Rua Copacabana, 45 - Rio de Janeiro/RJ', DATE '2024-02-01');
INSERT INTO TUTOR (ID_TUTOR, NOME, CPF, TELEFONE, EMAIL, ENDERECO, DATA_CADASTRO) VALUES (4,'Diego Almeida','444.555.666-77','(31) 91234-5604','diego.almeida@email.com','Rua Minas, 78 - Belo Horizonte/MG', DATE '2024-02-20');
INSERT INTO TUTOR (ID_TUTOR, NOME, CPF, TELEFONE, EMAIL, ENDERECO, DATA_CADASTRO) VALUES (5,'Fernanda Costa','555.666.777-88','(41) 91234-5605','fernanda.costa@email.com','Rua Curitiba, 300 - Curitiba/PR', DATE '2024-03-05');
INSERT INTO TUTOR (ID_TUTOR, NOME, CPF, TELEFONE, EMAIL, ENDERECO, DATA_CADASTRO) VALUES (6,'Gabriel Rocha','666.777.888-99','(51) 91234-5606','gabriel.rocha@email.com','Av. Ipiranga, 500 - Porto Alegre/RS', DATE '2024-03-18');
INSERT INTO TUTOR (ID_TUTOR, NOME, CPF, TELEFONE, EMAIL, ENDERECO, DATA_CADASTRO) VALUES (7,'Helena Martins','777.888.999-00','(81) 91234-5607','helena.martins@email.com','Rua Recife, 150 - Recife/PE', DATE '2024-04-02');
INSERT INTO TUTOR (ID_TUTOR, NOME, CPF, TELEFONE, EMAIL, ENDERECO, DATA_CADASTRO) VALUES (8,'Igor Nogueira','888.999.000-11','(61) 91234-5608','igor.nogueira@email.com','SQN 210 - Brasilia/DF', DATE '2024-04-25');
INSERT INTO TUTOR (ID_TUTOR, NOME, CPF, TELEFONE, EMAIL, ENDERECO, DATA_CADASTRO) VALUES (9,'Juliana Pires','999.000.111-22','(85) 91234-5609','juliana.pires@email.com','Av. Beira Mar, 88 - Fortaleza/CE', DATE '2024-05-10');
INSERT INTO TUTOR (ID_TUTOR, NOME, CPF, TELEFONE, EMAIL, ENDERECO, DATA_CADASTRO) VALUES (10,'Marcos Vinicius Teixeira','000.111.222-33','(71) 91234-5610','marcos.teixeira@email.com','Rua Salvador, 60 - Salvador/BA', DATE '2024-05-30');

-- VETERINARIO
INSERT INTO VETERINARIO (ID_VETERINARIO, NOME, CRMV, ESPECIALIDADE, TELEFONE, EMAIL) VALUES (1,'Dra. Patricia Gomes','CRMV-SP 12345','Clinica Geral','(11) 3222-1001','patricia.gomes@kuravet.com');
INSERT INTO VETERINARIO (ID_VETERINARIO, NOME, CRMV, ESPECIALIDADE, TELEFONE, EMAIL) VALUES (2,'Dr. Rafael Andrade','CRMV-SP 12346','Dermatologia','(11) 3222-1002','rafael.andrade@kuravet.com');
INSERT INTO VETERINARIO (ID_VETERINARIO, NOME, CRMV, ESPECIALIDADE, TELEFONE, EMAIL) VALUES (3,'Dra. Camila Duarte','CRMV-RJ 22345','Cardiologia','(21) 3222-1003','camila.duarte@kuravet.com');
INSERT INTO VETERINARIO (ID_VETERINARIO, NOME, CRMV, ESPECIALIDADE, TELEFONE, EMAIL) VALUES (4,'Dr. Bruno Cardoso','CRMV-MG 32345','Ortopedia','(31) 3222-1004','bruno.cardoso@kuravet.com');
INSERT INTO VETERINARIO (ID_VETERINARIO, NOME, CRMV, ESPECIALIDADE, TELEFONE, EMAIL) VALUES (5,'Dra. Larissa Ferreira','CRMV-PR 42345','Clinica Geral','(41) 3222-1005','larissa.ferreira@kuravet.com');
INSERT INTO VETERINARIO (ID_VETERINARIO, NOME, CRMV, ESPECIALIDADE, TELEFONE, EMAIL) VALUES (6,'Dr. Eduardo Santos','CRMV-RS 52345','Cirurgia','(51) 3222-1006','eduardo.santos@kuravet.com');
INSERT INTO VETERINARIO (ID_VETERINARIO, NOME, CRMV, ESPECIALIDADE, TELEFONE, EMAIL) VALUES (7,'Dra. Renata Barbosa','CRMV-PE 62345','Oncologia','(81) 3222-1007','renata.barbosa@kuravet.com');
INSERT INTO VETERINARIO (ID_VETERINARIO, NOME, CRMV, ESPECIALIDADE, TELEFONE, EMAIL) VALUES (8,'Dr. Felipe Ramos','CRMV-DF 72345','Clinica Geral','(61) 3222-1008','felipe.ramos@kuravet.com');
INSERT INTO VETERINARIO (ID_VETERINARIO, NOME, CRMV, ESPECIALIDADE, TELEFONE, EMAIL) VALUES (9,'Dra. Vanessa Lopes','CRMV-CE 82345','Nutricao','(85) 3222-1009','vanessa.lopes@kuravet.com');
INSERT INTO VETERINARIO (ID_VETERINARIO, NOME, CRMV, ESPECIALIDADE, TELEFONE, EMAIL) VALUES (10,'Dr. Thiago Moreira','CRMV-BA 92345','Clinica Geral','(71) 3222-1010','thiago.moreira@kuravet.com');

-- PET
INSERT INTO PET (ID_PET, NOME, ESPECIE, RACA, DATA_NASCIMENTO, SEXO, ID_TUTOR) VALUES (1,'Thor','Cachorro','Labrador', DATE '2022-03-15','M',1);
INSERT INTO PET (ID_PET, NOME, ESPECIE, RACA, DATA_NASCIMENTO, SEXO, ID_TUTOR) VALUES (2,'Mel','Gato','SRD', DATE '2021-07-20','F',2);
INSERT INTO PET (ID_PET, NOME, ESPECIE, RACA, DATA_NASCIMENTO, SEXO, ID_TUTOR) VALUES (3,'Bidu','Cachorro','Poodle', DATE '2019-11-05','M',3);
INSERT INTO PET (ID_PET, NOME, ESPECIE, RACA, DATA_NASCIMENTO, SEXO, ID_TUTOR) VALUES (4,'Luna','Gato','Siames', DATE '2023-01-10','F',4);
INSERT INTO PET (ID_PET, NOME, ESPECIE, RACA, DATA_NASCIMENTO, SEXO, ID_TUTOR) VALUES (5,'Rex','Cachorro','Pastor Alemao', DATE '2020-05-25','M',5);
INSERT INTO PET (ID_PET, NOME, ESPECIE, RACA, DATA_NASCIMENTO, SEXO, ID_TUTOR) VALUES (6,'Nina','Gato','Persa', DATE '2022-09-12','F',6);
INSERT INTO PET (ID_PET, NOME, ESPECIE, RACA, DATA_NASCIMENTO, SEXO, ID_TUTOR) VALUES (7,'Toby','Cachorro','Beagle', DATE '2021-02-18','M',7);
INSERT INTO PET (ID_PET, NOME, ESPECIE, RACA, DATA_NASCIMENTO, SEXO, ID_TUTOR) VALUES (8,'Mimi','Gato','SRD', DATE '2023-06-30','F',8);
INSERT INTO PET (ID_PET, NOME, ESPECIE, RACA, DATA_NASCIMENTO, SEXO, ID_TUTOR) VALUES (9,'Zeus','Cachorro','Rottweiler', DATE '2018-12-01','M',9);
INSERT INTO PET (ID_PET, NOME, ESPECIE, RACA, DATA_NASCIMENTO, SEXO, ID_TUTOR) VALUES (10,'Belinha','Cachorro','Shih Tzu', DATE '2024-02-14','F',10);

-- CONSULTA
INSERT INTO CONSULTA (ID_CONSULTA, ID_PET, ID_VETERINARIO, DATA_CONSULTA, TIPO_CONSULTA, DIAGNOSTICO, STATUS) VALUES (1,1,1, DATE '2025-01-10','Checkup','Animal saudavel, vacinacao em dia','REALIZADA');
INSERT INTO CONSULTA (ID_CONSULTA, ID_PET, ID_VETERINARIO, DATA_CONSULTA, TIPO_CONSULTA, DIAGNOSTICO, STATUS) VALUES (2,2,2, DATE '2025-02-14','Dermatologia','Dermatite alergica leve','REALIZADA');
INSERT INTO CONSULTA (ID_CONSULTA, ID_PET, ID_VETERINARIO, DATA_CONSULTA, TIPO_CONSULTA, DIAGNOSTICO, STATUS) VALUES (3,3,3, DATE '2025-03-05','Cardiologia','Sopro cardiaco grau I, monitorar','REALIZADA');
INSERT INTO CONSULTA (ID_CONSULTA, ID_PET, ID_VETERINARIO, DATA_CONSULTA, TIPO_CONSULTA, DIAGNOSTICO, STATUS) VALUES (4,4,1, DATE '2025-04-18','Vacinacao','Aplicada V4 felina','REALIZADA');
INSERT INTO CONSULTA (ID_CONSULTA, ID_PET, ID_VETERINARIO, DATA_CONSULTA, TIPO_CONSULTA, DIAGNOSTICO, STATUS) VALUES (5,5,4, DATE '2025-05-22','Ortopedia','Displasia coxofemoral leve','REALIZADA');
INSERT INTO CONSULTA (ID_CONSULTA, ID_PET, ID_VETERINARIO, DATA_CONSULTA, TIPO_CONSULTA, DIAGNOSTICO, STATUS) VALUES (6,6,5, DATE '2025-06-30','Checkup','Sem alteracoes','REALIZADA');
INSERT INTO CONSULTA (ID_CONSULTA, ID_PET, ID_VETERINARIO, DATA_CONSULTA, TIPO_CONSULTA, DIAGNOSTICO, STATUS) VALUES (7,7,6, DATE '2025-07-11','Cirurgia','Castracao eletiva realizada','REALIZADA');
INSERT INTO CONSULTA (ID_CONSULTA, ID_PET, ID_VETERINARIO, DATA_CONSULTA, TIPO_CONSULTA, DIAGNOSTICO, STATUS) VALUES (8,8,7, DATE '2025-08-09','Oncologia','Nodulo mamario em investigacao','REALIZADA');
INSERT INTO CONSULTA (ID_CONSULTA, ID_PET, ID_VETERINARIO, DATA_CONSULTA, TIPO_CONSULTA, DIAGNOSTICO, STATUS) VALUES (9,9,8, DATE '2025-09-25','Checkup','Peso acima do ideal, dieta recomendada','REALIZADA');
INSERT INTO CONSULTA (ID_CONSULTA, ID_PET, ID_VETERINARIO, DATA_CONSULTA, TIPO_CONSULTA, DIAGNOSTICO, STATUS) VALUES (10,10,9, DATE '2026-01-15','Nutricao','Ajuste de dieta para filhote','AGENDADA');

-- FATO_PAGAMENTO
INSERT INTO FATO_PAGAMENTO (ID_PAGAMENTO, ID_CONSULTA, CLINICA, TIPO_PAGAMENTO, VALOR, DATA_PAGAMENTO) VALUES (1,1,'KuraVet Pinheiros','Pix',150.00, DATE '2025-01-10');
INSERT INTO FATO_PAGAMENTO (ID_PAGAMENTO, ID_CONSULTA, CLINICA, TIPO_PAGAMENTO, VALOR, DATA_PAGAMENTO) VALUES (2,2,'KuraVet Pinheiros','Pix',180.00, DATE '2025-02-14');
INSERT INTO FATO_PAGAMENTO (ID_PAGAMENTO, ID_CONSULTA, CLINICA, TIPO_PAGAMENTO, VALOR, DATA_PAGAMENTO) VALUES (3,3,'KuraVet Pinheiros','Cartao de Credito',220.00, DATE '2025-03-05');
INSERT INTO FATO_PAGAMENTO (ID_PAGAMENTO, ID_CONSULTA, CLINICA, TIPO_PAGAMENTO, VALOR, DATA_PAGAMENTO) VALUES (4,4,'KuraVet Moema','Pix',90.00, DATE '2025-04-18');
INSERT INTO FATO_PAGAMENTO (ID_PAGAMENTO, ID_CONSULTA, CLINICA, TIPO_PAGAMENTO, VALOR, DATA_PAGAMENTO) VALUES (5,5,'KuraVet Moema','Cartao de Credito',350.00, DATE '2025-05-22');
INSERT INTO FATO_PAGAMENTO (ID_PAGAMENTO, ID_CONSULTA, CLINICA, TIPO_PAGAMENTO, VALOR, DATA_PAGAMENTO) VALUES (6,6,'KuraVet Moema','Cartao de Credito',130.00, DATE '2025-06-30');
INSERT INTO FATO_PAGAMENTO (ID_PAGAMENTO, ID_CONSULTA, CLINICA, TIPO_PAGAMENTO, VALOR, DATA_PAGAMENTO) VALUES (7,7,'KuraVet Moema','Dinheiro',200.00, DATE '2025-07-11');
INSERT INTO FATO_PAGAMENTO (ID_PAGAMENTO, ID_CONSULTA, CLINICA, TIPO_PAGAMENTO, VALOR, DATA_PAGAMENTO) VALUES (8,8,'KuraVet Alphaville','Pix',275.00, DATE '2025-08-09');
INSERT INTO FATO_PAGAMENTO (ID_PAGAMENTO, ID_CONSULTA, CLINICA, TIPO_PAGAMENTO, VALOR, DATA_PAGAMENTO) VALUES (9,9,'KuraVet Alphaville','Cartao de Credito',310.00, DATE '2025-09-25');
INSERT INTO FATO_PAGAMENTO (ID_PAGAMENTO, ID_CONSULTA, CLINICA, TIPO_PAGAMENTO, VALOR, DATA_PAGAMENTO) VALUES (10,10,'KuraVet Alphaville','Dinheiro',95.00, DATE '2026-01-15');